language: python
sudo: false

env:
  - LUA="lua 5.1"
  - LUA="lua 5.2"
  - LUA="lua 5.3"
  - LUA="luajit 2.0"

before_install:
  - pip install hererocks
  - hererocks l -r^ --$LUA
  - export PATH=$PATH:$PWD/l/bin
  - luarocks install luacheck
  - luarocks install busted
  - luarocks install luacov-coveralls

install:
  - luarocks make

script:
  - luacheck .
  - busted -c

after_success:
  - luacov-coveralls
